# Generated by Django 2.2.28 on 2023-03-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20230303_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='display_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_name', to='chat.UserProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chat.UserProfile'),
        ),
    ]
