# Generated by Django 2.2.28 on 2023-03-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20230304_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
