# Generated by Django 2.2.28 on 2023-03-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
