# Generated by Django 2.2.28 on 2023-03-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20230304_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time_stamp',
        ),
    ]
