# Generated by Django 2.2.28 on 2023-03-10 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 18, 43, 40, 319500, tzinfo=utc)),
        ),
    ]
