# Generated by Django 2.2.28 on 2023-03-10 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20230310_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 19, 40, 2, 625786, tzinfo=utc)),
        ),
    ]
