# Generated by Django 2.2.28 on 2023-03-10 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20230310_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 19, 43, 53, 726595, tzinfo=utc)),
        ),
    ]
