# Generated by Django 2.2.28 on 2023-03-10 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20230310_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 19, 46, 25, 751775, tzinfo=utc)),
        ),
    ]
