# Generated by Django 2.2.28 on 2023-03-11 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20230311_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 13, 26, 28, 849027, tzinfo=utc)),
        ),
    ]
